# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j0U7xZ9Wkixqd0XY-glskJS0_KB7zI1A
"""

#請在colab執行

!git clone https://github.com/yoyoLin427/bird_classification_effnet.git

"""# load model"""

import tensorflow as tf
model = tf.keras.models.load_model('/content/bird_classification_effnet/model_v11.h5')
model.summary()

"""# submission"""

class_path = '/content/bird_classification_effnet/classes.txt'
with open(class_path) as f:
  classes = [x.strip() for x in f.readlines()]  # all the testing images
classes

import os
import numpy as np
import numpy as np
from keras.preprocessing.image import img_to_array, load_img


with open('/content/bird_classification_effnet/testing_img_order.txt') as f:
     test_images = [x.strip() for x in f.readlines()]  # all the testing images

submission = []
i=0
for img_name in test_images:  # image order is important to your result
  img_path = '/content/bird_classification_effnet/testing_images/'+img_name
  img = load_img(img_path, target_size=(448, 448))  # this is a PIL image
  x = img_to_array(img)  # Numpy array with shape (150, 150, 3)
  x = x.reshape((1,) + x.shape)  # Numpy array with shape (1, 150, 150, 3)

  result = model.predict(x)
  cn = np.argmax(result,axis=1)
  submission.append([img_name, classes[cn[0]]])
  i +=1
  print(i)
  print([img_name, classes[cn[0]]])

np.savetxt('answer.txt', submission, fmt='%s')

from google.colab import files
files.download('answer.txt')